### ISSUE TITLE
Docs: Create GitHub Templates

### ISSUE THREAD

**Issue by JasinskiSz** [JasinskiSz/resuto-manager#1]
# Epic Title

Docs: Create GitHub Templates

### Motivation

Main part here is to keep the project tidy and organized. It's important if it'll see outside world.

### Goals

Create and add to the project:
- pull request template
- bug report template
- issues template for small and bigger tasks

## Tasks

- [x] [Task: Create Epic Issue Template](https://github.com/JasinskiSz/resuto-manager/issues/4)
- [x] [Task: Create Task Issue Template](https://github.com/JasinskiSz/resuto-manager/issues/5)
- [x] [Task: Create Pull Request Template](https://github.com/JasinskiSz/resuto-manager/issues/2)
- [x] [Task: Create Bug Report Template](https://github.com/JasinskiSz/resuto-manager/issues/3)
