### ISSUE TITLE
Feat: Simple Frontend Application

### ISSUE THREAD

**Issue by JasinskiSz** [JasinskiSz/resuto-manager#9]
# Epic Title

Feat: Simple Frontend Application 

## Description

It'd be a small challenge to create a frontend application alongside backend service.
A good time to also refresh the knowledge on this technology and React itself. 

### Motivation

Frontend application can be much more appealing to eyes than just a code (to some at least). It'd be great to have a frontend service app for the backend service.

### Goals

- Implement simple frontend application
  - should be written using React (optional/preference)

**TBD** probably.

## Tasks

- [ ] [Task: Base Skeleton For Frontend with Vite](https://github.com/JasinskiSz/resuto-manager/issues/10) 
- [ ] [Task: Update .gitignore File](https://github.com/JasinskiSz/resuto-manager/issues/11) 
- [ ] [Task: Setup ESLint for Frontend](https://github.com/JasinskiSz/resuto-manager/issues/14)
